CREATE TABLE books (
  id VARCHAR(255) PRIMARY KEY UNIQUE NOT NULL,
  title VARCHAR(255) UNIQUE NOT NULL,
  relative_cover_path VARCHAR(255),
  genre_id VARCHAR(255),
  author_id VARCHAR(255) NOT NULL,
  lector_id VARCHAR(255),
  FOREIGN KEY (genre_id) REFERENCES genres (id),
  FOREIGN KEY (author_id) REFERENCES authors (id),
  FOREIGN KEY (lector_id) REFERENCES lectors (id)
);

CREATE TABLE authors (
  id VARCHAR(255) PRIMARY KEY UNIQUE NOT NULL,
  name VARCHAR(255) UNIQUE NOT NULL,
  relative_img_path VARCHAR(255)
);

CREATE TABLE lectors (
  id VARCHAR(255) PRIMARY KEY UNIQUE NOT NULL,
  name VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE genres (
  id VARCHAR(255) PRIMARY KEY UNIQUE NOT NULL,
  name VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE tags (
  id VARCHAR(255) PRIMARY KEY UNIQUE NOT NULL,
  name VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE tags_authors (
  id VARCHAR(255) PRIMARY KEY UNIQUE NOT NULL,
  tag_id VARCHAR(255) NOT NULL,
  author_id VARCHAR(255) NOT NULL,
  FOREIGN KEY (tag_id) REFERENCES tags (id),
  FOREIGN KEY (author_id) REFERENCES authors (id)
);

CREATE TABLE tags_books (
  id VARCHAR(255) PRIMARY KEY UNIQUE NOT NULL,
  tag_id VARCHAR(255) NOT NULL,
  book_id VARCHAR(255) NOT NULL,
  FOREIGN KEY (tag_id) REFERENCES tags (id),
  FOREIGN KEY (book_id) REFERENCES books (id)
);

CREATE TABLE books_read (
  id VARCHAR(255) PRIMARY KEY UNIQUE NOT NULL,
  book_id VARCHAR(255) NOT NULL,
  rate INT,
  tier INT,
  note VARCHAR(511),
  FOREIGN KEY (book_id) REFERENCES books (id)
);

CREATE TABLE absolute_paths (
  id VARCHAR(255) PRIMARY KEY UNIQUE NOT NULL,
  name VARCHAR(255) UNIQUE NOT NULL,
  path VARCHAR(255) UNIQUE NOT NULL
);
